# Generated by Django 5.1.3 on 2024-12-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSchoolWebsFetchedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(max_length=225)),
                ('web_name', models.CharField(max_length=225)),
                ('true_web', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('details', models.CharField(blank=True, max_length=225, null=True)),
                ('drive_link', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('other_links', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flight_school_webs_fetched_data_new',
            },
        ),
        migrations.CreateModel(
            name='FlightSchoolWebsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('web_name', models.TextField()),
            ],
            options={
                'db_table': 'flight_school_webs_new',
            },
        ),
        migrations.CreateModel(
            name='ScrapingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_web_name', models.CharField(max_length=225)),
                ('last_web_url', models.CharField(max_length=225)),
                ('internal_links', models.CharField(blank=True, max_length=225, null=True)),
                ('fetching_started_on', models.CharField(blank=True, max_length=45, null=True)),
                ('fetching_completed_on', models.CharField(blank=True, max_length=45, null=True)),
                ('successful_fetching', models.BooleanField(default=False)),
                ('details', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'scraping_status',
            },
        ),
    ]
