# Generated by Django 5.1.3 on 2024-12-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='internal_links',
        ),
    ]
