# Generated by Django 5.1.3 on 2024-12-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_task', '0002_remove_scrapingstatus_internal_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingstatus',
            name='fetching_started_on',
        ),
    ]
