# Generated by Django 5.1.3 on 2024-12-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_task', '0003_remove_scrapingstatus_fetching_started_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingstatus',
            name='fetching_started_on',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='scrapingstatus',
            name='internal_links',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
