# Generated by Django 5.1.3 on 2024-12-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_task', '0004_scrapingstatus_fetching_started_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingstatus',
            name='remaining_webs',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
