# Generated by Django 5.1.3 on 2024-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_task', '0005_scrapingstatus_remaining_webs'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschoolwebsfetcheddata',
            name='content_length',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='flightschoolwebsfetcheddata',
            name='fetched_on',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
