# Generated by Django 5.1.3 on 2025-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_task', '0008_scrapingstatus_chunk_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschoolwebsfetcheddata',
            name='flight_web',
            field=models.BooleanField(default=False),
        ),
    ]
